app:
  title: "Fraud Analytics and ML Detection"

data:
  use_database: true

database:
  host: "localhost"
  port: 5432
  dbname: "fraud_db"
  user: "postgres"
  password: "postgresXXX"
  schema: "fraud"

tables:
  train: fraud.transaction_train
  test: fraud.transaction_test

files:
  train_csv: "https://github.com/user-attachments/files/25766799/transactions_train.zip"
  test_csv: "https://github.com/user-attachments/files/25766793/transactions_test.zip"

model:
  path: models/fraud_model.pkl
  preprocessor: models/preprocessor.pkl
  selector: models/selector.pkl
  algorithm: AdaBoost
  auc_score: 0.84

tableau:
  dashboard_url: "https://public.tableau.com/views/FraudVisualizationAnalyticv1/TimeBehaviouralPattern?:language=en-US&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link"
